services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: mys-be:1.1
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: mys-fe:1.1
    ports:
      - "3000:3000"