services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      network: host
    image: mys-be:1.1
    network_mode: host

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      network: host
    image: mys-fe:1.1
    ports:
     - "3000:3000"
